/**
 * BrandMind — AI-Powered Semantic Idea Ingestion
 *
 * Architecture:
 *   User enters ANY idea
 *        ↓
 *   Gemini 2.5 Flash (Thinking Model) via /api/gemini
 *        ↓
 *   Structured JSON semantic blueprint
 *        ↓
 *   Agent pipeline (Discover → Position → Shape → Visualize → Challenge → Deliver)
 *
 * NO hardcoded templates. NO predefined archetypes. NO fake scores.
 * Every output is generated by Gemini from the user's actual words.
 */

import { executeStagePrompt } from '../services/aiEngine.js';

/**
 * Returns true if the idea is too short to meaningfully analyze.
 */
export function isIdeaThin(idea = '') {
  const words = idea.trim().split(/\s+/).filter(Boolean);
  return words.length < 9;
}

/**
 * Minimal safe fallback — used ONLY when the network is down or API fails.
 * Returns null values instead of fabricating fake analysis.
 */
function buildNetworkFallback(originalIdea, clarificationAnswers = '') {
  return {
    ideaType: null,
    problem: null,
    targetAudience: null,
    userNeed: null,
    solution: null,
    category: null,
    differentiation: null,
    brandDirection: null,
    domain: null,
    actors: null,
    activity: null,
    desiredOutcome: null,
    plainSummary: null,
    baseName: null,
    score: null,
    isThin: isIdeaThin(originalIdea),
    wordCount: originalIdea.trim().split(/\s+/).filter(Boolean).length,
    originalIdea,
    clarificationAnswers,
    suggestedQuestions: [],
    _fallback: true,
    _error: 'AI analysis unavailable — please check your connection and API key.'
  };
}

/**
 * AI-Powered Semantic Ingestion
 *
 * Sends the raw user idea to Gemini 2.5 Flash (thinking model) with a
 * rich, multi-dimensional reasoning prompt. The model thinks across domain,
 * audience, differentiation, feasibility, and naming before responding.
 *
 * No templates. No string manipulation. The AI does ALL the thinking.
 */
export async function parseIdeaWithAI(originalIdea = '', clarificationAnswers = '') {
  const isThin = isIdeaThin(originalIdea);
  const wordCount = originalIdea.trim().split(/\s+/).filter(Boolean).length;

  const prompt = `You are the Semantic Ingestion Engine for BrandMind, an AI-powered brand strategy platform.

A user has submitted a raw idea. Your task is to deeply reason about what this idea actually IS, who it serves, what problem it solves, and what makes it unique — then output a rich, structured JSON blueprint.

Rules:
- Work from the user's EXACT words. Do not genericize or reframe into a different idea.
- Never output placeholder text like "To be determined", "N/A", or "Various".
- Score honestly — a vague idea should score low; a sharp idea should score high.
- If the idea is ambiguous, reflect that in the score and ask targeted questions.
- Do NOT use buzzwords: no "seamless", "leverage", "synergy", "revolutionize", "disruptive".
- Use plain, specific, human language. Write like a sharp strategist, not a marketer.

User Idea: "${originalIdea}"
${clarificationAnswers ? `User Clarification: "${clarificationAnswers}"` : ''}

Think through these dimensions before responding:
1. What domain/industry does this actually belong to? Be specific.
2. Who specifically will use this — what is their daily frustration?
3. What is the core value exchange between user and product?
4. What already exists in this space, and how is this genuinely different?
5. How hard is this to actually build and launch?
6. What short, memorable name captures the essence of this idea?

Return ONLY a valid JSON object — no markdown fences, no explanation text before or after:
{
  "ideaType": "One of: mobile_app | saas | marketplace | physical_product | food_business | service | community | education | healthcare | fintech | hardware | other",
  "problem": "The specific real-world pain this solves — one concrete sentence from the user's perspective",
  "targetAudience": "The specific primary user — be precise, not generic (e.g. 'Freelance UX designers managing 3+ simultaneous client projects')",
  "userNeed": "What they emotionally and practically want — not a feature, but a feeling or real outcome",
  "solution": "How this idea concretely solves the problem — specific to this idea, not a generic description",
  "category": "The market category in plain terms (e.g. 'Fitness Habit Tracking', 'Peer-to-Peer Tool Lending')",
  "differentiation": "What genuinely makes this different from existing options — be specific, not 'better UX'",
  "brandDirection": "Tonal and visual identity appropriate for this audience (e.g. 'Warm and tactical — earthy tones, hand-drawn icons, community-first voice')",
  "domain": "The specific industry/domain space (e.g. 'Urban Micro-Gardening', 'Creator Economy Payments')",
  "actors": "All key people involved: primary users, operators, third parties (e.g. 'Home cooks & local organic farmers')",
  "activity": "The core repeated action a user takes with this product (e.g. 'Photographs a receipt and splits the bill in 10 seconds')",
  "desiredOutcome": "What success looks like for the user — tangible and emotional (e.g. 'Never feel guilty about food waste again')",
  "plainSummary": "One exciting, specific sentence explaining what this is — readable by anyone, no jargon",
  "baseName": "A short, catchy, memorable root word inspired by the idea's core meaning (2-8 chars, avoid generic suffixes like Hub, Pro, Go, App, Ify)",
  "score": {
    "overall": <integer 0-100, weighted average>,
    "rating": "<one of: 'Weak Concept' | 'Needs Work' | 'Solid Start' | 'Promising Idea' | 'Strong Concept' | 'Exceptional'>",
    "clarity": <integer 0-100, how clearly defined and specific the idea is>,
    "marketNeed": <integer 0-100, how strong the real-world demand signal is>,
    "originality": <integer 0-100, how differentiated from existing solutions>,
    "launchEase": <integer 0-100, how feasible it is to ship a working MVP>,
    "verdict": "One honest sentence — what is genuinely strong AND what is the biggest risk or gap"
  },
  "suggestedQuestions": [
    "The single most important clarifying question that would sharpen this idea most",
    "A second question targeting the biggest unknown or risk"
  ]
}`;

  try {
    const { result } = await executeStagePrompt({
      stageName: 'semantic_ingestion',
      prompt,
      fallbackFn: () => buildNetworkFallback(originalIdea, clarificationAnswers),
      context: { originalIdea, clarificationAnswers },
      parsedIdea: null
    });

    return {
      ...result,
      isThin,
      wordCount,
      originalIdea,
      clarificationAnswers,
      _fallback: false
    };
  } catch (err) {
    console.warn('[BrandMind] Semantic ingestion failed:', err);
    return buildNetworkFallback(originalIdea, clarificationAnswers);
  }
}

/**
 * Kept for backward-compat — components that call parseIdea() synchronously
 * now receive a null-value fallback instead of fake template data.
 * Prefer parseIdeaWithAI() for actual analysis.
 */
export function parseIdea(idea = '', clarificationAnswer = '') {
  return buildNetworkFallback(idea, clarificationAnswer);
}
